import {test,expect} from '@playwright/test';import fs from 'node:fs/promises';import {execFileSync} from 'node:child_process';
const demo=JSON.parse(await fs.readFile('fixtures/demo.json','utf8'));
test('real controls, imported hierarchy, four downloads, interruption and mobile layout',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const external=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173/'))external.push(r.url());});
 await page.goto('/');await expect(page.locator('#status')).toContainText('2 assertions failed');await expect(page.locator('.badge.fail')).toHaveCount(2);
 await page.getByRole('button',{name:'Keep exception last'}).click();await expect(page.locator('#status')).toContainText('Listed assertions passed');await expect(page.locator('.badge.pass')).toHaveCount(6);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download review pack'}).click();const download=await pending;const file=info.outputPath('review.zip');await download.saveAs(file);
 const unpacked=JSON.parse(execFileSync('python',['-c','import zipfile,json,sys; z=zipfile.ZipFile(sys.argv[1]); print(json.dumps({n:z.read(n).decode() for n in z.namelist()}))',file],{encoding:'utf8'}));expect(Object.keys(unpacked)).toEqual(['replacement.editorconfig','original.editorconfig','path-manifest.json','review-report.json']);expect(unpacked['original.editorconfig']).toBe(demo.configs[0].content);const report=JSON.parse(unpacked['review-report.json']);expect(report.status).toBe('assertions-passed');expect(report.rows[0].after.values.indent_size).toBe('3');
 const physical=JSON.parse(execFileSync('python',['scripts/python-oracle.py'],{input:JSON.stringify({manifest:JSON.parse(unpacked['path-manifest.json']),replacement:unpacked['replacement.editorconfig']}),encoding:'utf8'}));const physicalJs=JSON.parse(execFileSync('node',['scripts/js-physical-oracle.mjs'],{input:JSON.stringify({manifest:JSON.parse(unpacked['path-manifest.json']),replacement:unpacked['replacement.editorconfig']}),encoding:'utf8'}));for(const row of report.rows)for(const phase of ['before','after']){expect(row[phase].values).toEqual(physical[phase][row.path]);expect(physicalJs[phase][row.path]).toEqual(physical[phase][row.path]);}
 await page.locator('#replacement').fill(unpacked['replacement.editorconfig'].replace('end_of_line = lf','end_of_line = crlf'));await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#status')).toContainText('Replacement changed');await page.locator('#review').click();await expect(page.locator('#status')).toContainText('1 assertion failed');
 await page.locator('#replacement').fill(unpacked['replacement.editorconfig'].replace('root = true','root = false'));await page.locator('#review').click();await expect(page.locator('#status')).toContainText('Incomplete hierarchy');await expect(page.locator('#results')).toContainText('/.editorconfig');
 await page.locator('#replacement').fill('Root = true\n[*]\nindent_size = 2');await page.locator('#review').click();await expect(page.locator('#error')).toContainText('lowercase');await expect(page.locator('#download')).toBeDisabled();
 await page.locator('#load-demo').click();await expect(page.locator('#status')).toContainText('2 assertions failed');await page.locator('#target').selectOption('/demo/vendor/.editorconfig');await expect(page.locator('#original')).toContainText('indent_size = 8');await expect(page.locator('#status')).toContainText('assertion');await page.locator('#target').selectOption('/demo/.editorconfig');await expect(page.locator('#replacement')).toHaveValue(demo.configs[0].content+'\n[*.txt]\nindent_size = 3\n');
 await page.locator('#manifest-details').evaluate(el=>el.open=true);await page.locator('#manifest-input').fill(JSON.stringify({...demo,absent:[]}));await page.locator('#apply-manifest').click();await expect(page.locator('#status')).toContainText('Incomplete hierarchy');
 await page.locator('#load-demo').click();await expect(page.locator('#status')).toContainText('2 assertions failed');await page.locator('#fixed').click();await expect(page.locator('#status')).toContainText('Listed assertions passed');await page.screenshot({path:info.outputPath('desktop-review.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('mobile-review.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('enlarged-text-review.png'),fullPage:true});
 expect(errors).toEqual([]);expect(external).toEqual([]);await page.reload();await expect(page.locator('#status')).toContainText('2 assertions failed');
});
test('superseded file imports cannot overwrite newer intent; invalid imports are atomic',async({page})=>{
 await page.addInitScript(()=>{const native=File.prototype.text;File.prototype.text=function(){const file=this;if(file.name!=='slow.json')return native.call(file);return new Promise(resolve=>setTimeout(async()=>{resolve(await native.call(file));window.__slowReadDone=true;},300));};});
 await page.goto('/');await expect(page.locator('#status')).toContainText('2 assertions failed');
 const other={configs:[{path:'/other/.editorconfig',content:'root = true\n[*]\nindent_size = 9\n'}],paths:['/other/a.txt'],absent:[],target:'/other/.editorconfig',assertions:[]};
 await page.locator('#import-file').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(other))});await page.locator('#load-demo').click();await page.waitForFunction(()=>window.__slowReadDone===true);await expect(page.locator('#target')).toHaveValue('/demo/.editorconfig');
 const tooMany={...demo,configs:Array.from({length:20000},(_,i)=>({path:`/a${i}/.editorconfig`,content:''}))};await page.locator('#import-file').setInputFiles({name:'oversized-count.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(tooMany))});await expect(page.locator('#error')).toContainText('Import rejected; the previous scope is unchanged');await expect(page.locator('#target option')).toHaveCount(2);
 await page.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(other))});await expect(page.locator('#target')).toHaveValue('/other/.editorconfig');await expect(page.locator('#status')).toContainText('No assertions supplied');
});
test('worker initialization failure is reported without stale downloadable success',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.Worker=undefined;});await page.goto('/');await expect(page.locator('#status')).toContainText('Review blocked');await expect(page.locator('#error')).toContainText('could not start');await expect(page.locator('#download')).toBeDisabled();expect(errors).toEqual([]);});
