import esbuild from 'esbuild';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);await fs.mkdir('dist',{recursive:true});
const notices=[];
const runtimePackages=['editorconfig','@one-ini/wasm','minimatch','brace-expansion','balanced-match','semver','buffer','base64-js','ieee754','path-browserify'];
for(const name of runtimePackages){const base=path.resolve('node_modules',name),pkg=JSON.parse(await fs.readFile(path.join(base,'package.json'),'utf8'));const candidates=['LICENSE','LICENSE.md','LICENSE.txt'];let license;for(const candidate of candidates){try{license=await fs.readFile(path.join(base,candidate),'utf8');break;}catch{}}if(!license)throw Error(`Missing license for ${name}`);notices.push(`${name} ${pkg.version}\nLicense declared: ${pkg.license}\n${license}`);}
const banner='IndentDelta third-party notices\n\nThese licenses apply only to the named third-party dependencies. No license grant for original IndentDelta code is made by these notices.\n\n';
await fs.writeFile('dist/THIRD-PARTY-NOTICES.txt',banner+notices.join('\n\n------------------------------\n\n'));
const plugin={name:'official-editorconfig-browser-adapter',setup(build){build.onResolve({filter:/^(node:)?(fs|path|buffer)$/},args=>{if(args.path.endsWith('fs'))return{path:'disabled-fs',namespace:'indent-delta'};return {path:require.resolve(args.path.endsWith('path')?'path-browserify':'buffer/')};});build.onLoad({filter:/.*/,namespace:'indent-delta'},()=>({contents:'export function readFileSync(){throw Error("Filesystem access is disabled; use imported text only")} export function readFile(){throw Error("Filesystem access is disabled; use imported text only")}',loader:'js'}));build.onLoad({filter:/one_ini\.js$/},async args=>{let contents=await fs.readFile(args.path,'utf8');const original="const wasmPath = `${__dirname}/one_ini_bg.wasm`;\nconst wasmBytes = require('fs').readFileSync(wasmPath);";if(!contents.includes(original))throw Error('Pinned official WASM initialization changed; review adapter');const wasm=await fs.readFile(path.join(path.dirname(args.path),'one_ini_bg.wasm'));contents=contents.replace(original,`const wasmBytes = Uint8Array.from(atob('${wasm.toString('base64')}'), c => c.charCodeAt(0));`);return{contents,loader:'js',resolveDir:path.dirname(args.path)};});}};
const result=await esbuild.build({entryPoints:['src/app.js','src/worker.js'],outdir:'dist',bundle:true,format:'esm',platform:'browser',target:['es2022'],minify:true,metafile:true,plugins:[plugin],define:{'process.cwd':'indentDeltaCwd','process.platform':'"browser"','process.env.NODE_DEBUG':'""'},banner:{js:'const indentDeltaCwd = () => "/";'},legalComments:'eof'});
await fs.writeFile('evidence/browser-bundle-metafile.json',JSON.stringify(result.metafile,null,2));
for(const name of ['index.html','style.css'])await fs.copyFile('public/'+name,'dist/'+name);
await fs.copyFile('fixtures/demo.json','dist/demo-manifest.json');
console.log('Built static offline app; official parser unchanged except deterministic WASM-byte loading. Dependency notices included.');
