import {readFile,writeFile,mkdir} from 'node:fs/promises';import {spawnSync} from 'node:child_process';import {review} from '../src/engine.js';
const demo=JSON.parse(await readFile('fixtures/demo.json','utf8'));const original=demo.configs[0].content;
const scenarios=[
 {name:'naive_append',manifest:demo,replacement:original+'\n[*.txt]\nindent_size = 3\n'},
 {name:'corrected_exception_last',manifest:demo,replacement:original.replace('indent_size = 4','indent_size = 3')},
 {name:'remove_root',manifest:demo,replacement:original.replace('root = true','root = false')},
 {name:'protected_property',manifest:demo,replacement:original.replace('indent_size = 4','indent_size = 3').replace('end_of_line = lf','end_of_line = crlf')},
 {name:'unset_derived_duplicates_no_match',manifest:{configs:[{path:'/case/.editorconfig',content:'root = true\n[*.txt]\nindent_size = 2\nindent_size = 4\ncharset = utf-8\n[unset.txt]\ncharset = unset\n[tab.txt]\nindent_style = tab\nindent_size = tab\ntab_width = 6\n'}],absent:[],paths:['/case/normal.txt','/case/unset.txt','/case/tab.txt','/case/no-match.c'],target:'/case/.editorconfig',assertions:[]},replacement:'root = true\n[*.txt]\nindent_size = 2\nindent_size = 4\ncharset = utf-8\n[unset.txt]\ncharset = unset\n[tab.txt]\nindent_style = tab\nindent_size = tab\ntab_width = 6\n'},
 {name:'ancestors_and_nested_root',manifest:{configs:[{path:'/.editorconfig',content:'root = true\n[*]\nindent_size = 7\ncharset = utf-8\n'},{path:'/case/.editorconfig',content:'[*.txt]\nindent_size = 2\n'},{path:'/case/vendor/.editorconfig',content:'root = true\n[*]\nindent_size = 8\n'}],absent:['/case/docs/.editorconfig'],paths:['/case/docs/prose.txt','/case/main.c','/case/vendor/lib.txt'],target:'/case/.editorconfig',assertions:[]},replacement:'[*.txt]\nindent_size = 3\n'}
];
await mkdir('evidence',{recursive:true});let checked=0;const summary=[];
for(const scenario of scenarios){const result=review(scenario.manifest,scenario.replacement);const py=spawnSync('python',['scripts/python-oracle.py'],{input:JSON.stringify(scenario),encoding:'utf8',env:{...process.env,PYTHONPATH:process.env.PYTHONPATH??'/tmp/indentdelta-python'}});if(py.status)throw Error(py.stderr);const oracle=JSON.parse(py.stdout);const js=spawnSync('node',['scripts/js-physical-oracle.mjs'],{input:JSON.stringify(scenario),encoding:'utf8'});if(js.status)throw Error(js.stderr);const physicalJs=JSON.parse(js.stdout);for(const row of result.rows)for(const phase of ['before','after']){if(!row[phase])continue;const expected=oracle[phase][row.path];if(JSON.stringify(Object.entries(physicalJs[phase][row.path]).sort())!==JSON.stringify(Object.entries(expected).sort()))throw Error('Physical JS/Python discrepancy in '+scenario.name);if(JSON.stringify(Object.entries(row[phase].values).sort())!==JSON.stringify(Object.entries(expected).sort()))throw Error(`${scenario.name} ${phase} ${row.path}: ${JSON.stringify(row[phase].values)} != ${JSON.stringify(expected)}`);checked++;}summary.push({name:scenario.name,status:result.status,matchedNativeResolutions:result.rows.flatMap(r=>[r.before,r.after]).filter(Boolean).length,failedAssertions:result.assertions.filter(a=>!a.passed).length,missing:result.missing});}
if(summary[0].failedAssertions!==2||summary[1].status!=='assertions-passed'||summary[2].status!=='incomplete'||summary[3].status!=='assertions-failed')throw Error('Negative controls failed');
const output={checkedAt:new Date().toISOString(),javascriptCore:'editorconfig 3.0.2',pythonCore:'EditorConfig 0.17.1',checkedResolutions:checked,scenarios:summary};await writeFile('evidence/native-parity.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2));
